repos:
-   repo: https://github.com/woile/commitizen
    rev: v2.17.13
    hooks:
    - id: commitizen
      stages: [commit-msg]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: clippy
